services:
  - type: web
    name: aerotoeic-api-gateway
    env: docker
    plan: free
    dockerfilePath: ./backend/api-gateway/Dockerfile
    envVars:
      - key: PORT
        value: 4000
      - key: ACCOUNT_SERVICE_URL
        value: http://aerotoeic-account-service:4001
      - key: EXAM_SERVICE_URL
        value: http://aerotoeic-exam-service:4002
      - key: CATALOG_SERVICE_URL
        value: http://aerotoeic-catalog-service:4003
      - key: ANALYTICS_SERVICE_URL
        value: http://aerotoeic-analytics-service:4004
      - key: AI_SERVICE_URL
        value: http://aerotoeic-ai-service:4005

  - type: web
    name: aerotoeic-account-service
    env: docker
    plan: free
    dockerfilePath: ./backend/account-service/Dockerfile
    envVars:
      - key: PORT
        value: 4001
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/auth_db?sslmode=require

  - type: web
    name: aerotoeic-exam-service
    env: docker
    plan: free
    dockerfilePath: ./backend/exam-service/Dockerfile
    envVars:
      - key: PORT
        value: 4002
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/exam_db?sslmode=require

  - type: web
    name: aerotoeic-catalog-service
    env: docker
    plan: free
    dockerfilePath: ./backend/catalog-service/Dockerfile
    envVars:
      - key: PORT
        value: 4003
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/catalog_db?sslmode=require

  - type: web
    name: aerotoeic-analytics-service
    env: docker
    plan: free
    dockerfilePath: ./backend/analytics-service/Dockerfile
    envVars:
      - key: PORT
        value: 4004
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/analytics_db?sslmode=require

  - type: web
    name: aerotoeic-ai-service
    env: docker
    plan: free
    dockerfilePath: ./backend/ai-service/Dockerfile
    envVars:
      - key: PORT
        value: 4005
