services:
  - type: web
    name: aerotoeic-api-gateway
    env: docker
    plan: free
    dockerfilePath: ./backend/api-gateway/Dockerfile
    dockerContext: ./backend/api-gateway
    envVars:
      - key: PORT
        value: 4000
      - key: ACCOUNT_SERVICE_URL
        value: https://aerotoeic-account-service.onrender.com
      - key: AUTH_SERVICE_URL
        value: https://aerotoeic-account-service.onrender.com
      - key: EXAM_SERVICE_URL
        value: https://aerotoeic-exam-service.onrender.com
      - key: CATALOG_SERVICE_URL
        value: https://aerotoeic-catalog-service.onrender.com
      - key: AI_SERVICE_URL
        value: https://aerotoeic-ai-service.onrender.com

  - type: web
    name: aerotoeic-account-service
    env: docker
    plan: free
    dockerfilePath: ./backend/account-service/Dockerfile
    dockerContext: ./backend/account-service
    envVars:
      - key: PORT
        value: 4001
      - key: DATABASE_URL
        fromDatabase:
          name: aerotoeic-db
          property: connectionString

  - type: web
    name: aerotoeic-exam-service
    env: docker
    plan: free
    dockerfilePath: ./backend/exam-service/Dockerfile
    dockerContext: ./backend/exam-service
    envVars:
      - key: PORT
        value: 4002
      - key: DATABASE_URL
        fromDatabase:
          name: aerotoeic-db
          property: connectionString

  - type: web
    name: aerotoeic-catalog-service
    env: docker
    plan: free
    dockerfilePath: ./backend/catalog-service/Dockerfile
    dockerContext: ./backend/catalog-service
    envVars:
      - key: PORT
        value: 4003
      - key: DATABASE_URL
        fromDatabase:
          name: aerotoeic-db
          property: connectionString

  - type: web
    name: aerotoeic-ai-service
    env: docker
    plan: free
    dockerfilePath: ./backend/ai-service/Dockerfile
    dockerContext: ./backend/ai-service
    envVars:
      - key: PORT
        value: 4005
      - key: DATABASE_URL
        fromDatabase:
          name: aerotoeic-db
          property: connectionString

databases:
  - name: aerotoeic-db
    plan: free
    databaseName: toeic_db
    user: toeic_user
